import { CalendarCheck, UserPlus, Users } from "lucide-react";
import { createAttendanceEventAction, createAttendancePersonAction, mapAttendancePersonAction, saveAttendanceRecordAction, toggleAttendanceEventAction, toggleAttendancePersonAction } from "@/app/actions/workflows";
import { PortalShell } from "@/components/portal-shell";
import { requireProfile } from "@/lib/auth";
import { daysAgoInIndia, displayDate, todayInIndia } from "@/lib/date";
import { getAttendanceEventPeople, getAttendanceEvents, getAttendancePeople, getAttendanceRecords, getProfiles } from "@/lib/data";

export default async function AttendancePage({ searchParams }: { searchParams: Promise<{ eventId?: string; date?: string }> }) {
  const profile = await requireProfile();
  const query = await searchParams;
  const students = profile.role === "student" ? [profile] : await getProfiles("student");
  const visibleProfileIds = profile.role === "super_admin" ? null : students.map((student) => student.id);
  const [events, people] = await Promise.all([getAttendanceEvents(), getAttendancePeople(visibleProfileIds)]);
  const visiblePersonIds = profile.role === "super_admin" ? null : people.map((person) => person.id);
  const [mappings, records] = await Promise.all([getAttendanceEventPeople(visiblePersonIds), getAttendanceRecords(daysAgoInIndia(30), visiblePersonIds)]);
  const selectedEvent = events.find((event) => event.id === query.eventId) ?? events[0];
  const selectedDate = /^\d{4}-\d{2}-\d{2}$/.test(query.date ?? "") ? query.date! : todayInIndia();
  const mappedIds = new Set(mappings.filter((item) => item.event_id === selectedEvent?.id).map((item) => item.person_id));
  const eventPeople = people.filter((person) => mappedIds.has(person.id));
  return <PortalShell profile={profile}><main className="page-container"><header className="page-heading hero-heading"><div><p className="eyebrow">Attendance</p><h1>Attendance Module</h1><p>{profile.role === "student" ? "Review your attendance across hostel events." : "Manage attendance securely through your portal role."}</p></div></header>
    {profile.role === "super_admin" ? <section className="dashboard-grid"><article className="panel"><div className="panel-title"><h2><UserPlus size={19} /> Add attendee</h2></div><form action={createAttendancePersonAction} className="form-stack"><div className="field"><label htmlFor="person-profile">Link student (optional)</label><select id="person-profile" name="profileId" defaultValue=""><option value="">External devotee</option>{students.filter((student) => !people.some((person) => person.profile_id === student.id)).map((student) => <option key={student.id} value={student.id}>{student.full_name}</option>)}</select></div><div className="field"><label htmlFor="person-name">Name</label><input id="person-name" name="name" required /></div><div className="field"><label htmlFor="person-phone">Phone</label><input id="person-phone" name="phone" /></div><div className="field"><label htmlFor="person-notes">Notes</label><textarea id="person-notes" name="notes" /></div><button className="button">Add attendee</button></form></article><article className="panel"><div className="panel-title"><h2><CalendarCheck size={19} /> Create event</h2></div><form action={createAttendanceEventAction} className="form-stack"><div className="field"><label htmlFor="event-name">Event name</label><input id="event-name" name="name" required /></div><div className="field"><label htmlFor="statuses">Statuses</label><input id="statuses" name="statuses" defaultValue="Present, Absent, Late" required /><p className="field-hint">Comma-separated, maximum eight options.</p></div><button className="button">Create event</button></form>{events.length && people.length ? <form action={mapAttendancePersonAction} className="form-stack mapping-form"><h3>Map attendee to event</h3><div className="field"><label>Event<select name="eventId" required>{events.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select></label></div><div className="field"><label>Attendee<select name="personId" required>{people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label></div><button className="button button-secondary">Add to event</button></form> : null}</article></section> : null}
    {profile.role !== "student" ? <section className="panel section-gap"><form className="filters" method="get"><div className="field"><label htmlFor="eventId">Event</label><select id="eventId" name="eventId" defaultValue={selectedEvent?.id}>{events.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select></div><div className="field"><label htmlFor="date">Date</label><input id="date" name="date" type="date" defaultValue={selectedDate} /></div><button className="button button-secondary">Load sheet</button></form><div className="panel-title"><h2>{selectedEvent?.name ?? "Attendance sheet"}</h2><span>{eventPeople.length} attendees</span></div><div className="attendance-sheet">{eventPeople.map((person) => { const current = records.find((record) => record.event_id === selectedEvent?.id && record.person_id === person.id && record.attendance_date === selectedDate); return <form action={saveAttendanceRecordAction} className="attendance-row" key={person.id}><input type="hidden" name="eventId" value={selectedEvent?.id} /><input type="hidden" name="personId" value={person.id} /><input type="hidden" name="attendanceDate" value={selectedDate} /><strong>{person.name}</strong><select name="status" defaultValue={current?.status ?? selectedEvent?.status_options[0]}>{selectedEvent?.status_options.map((status) => <option key={status} value={status}>{status}</option>)}</select><input name="remark" aria-label={`Remark for ${person.name}`} placeholder="Remark" defaultValue={current?.remark ?? ""} /><button className="button button-small">Save</button></form>; })}{!eventPeople.length ? <p className="empty-state">No visible attendees are mapped to this event.</p> : null}</div></section> : <section className="panel"><div className="panel-title"><h2><Users size={19} /> My attendance history</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Status</th><th>Remark</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{displayDate(record.attendance_date)}</td><td>{events.find((event) => event.id === record.event_id)?.name ?? "Event"}</td><td><span className="status-pill status-success">{record.status}</span></td><td>{record.remark ?? "—"}</td></tr>)}</tbody></table>{!records.length ? <p className="empty-state">No attendance records yet.</p> : null}</div></section>}
    {profile.role === "super_admin" ? <section className="panel section-gap"><div className="panel-title"><h2>Attendance setup</h2><span>Archive items without deleting history</span></div><div className="management-grid"><div><h3>Events</h3>{events.map((event) => <form action={toggleAttendanceEventAction} className="management-row" key={event.id}><span>{event.name}</span><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="active" value={event.is_active ? "false" : "true"} /><button className="button button-secondary button-small">{event.is_active ? "Archive" : "Restore"}</button></form>)}</div><div><h3>Attendees</h3>{people.map((person) => <form action={toggleAttendancePersonAction} className="management-row" key={person.id}><span>{person.name}</span><input type="hidden" name="personId" value={person.id} /><input type="hidden" name="active" value={person.is_active ? "false" : "true"} /><button className="button button-secondary button-small">{person.is_active ? "Archive" : "Restore"}</button></form>)}</div></div></section> : null}
    {profile.role !== "student" ? <section className="panel section-gap"><div className="panel-title"><h2>Recent attendance records</h2><span>Last 30 days</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Attendee</th><th>Status</th><th>Remark</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{displayDate(record.attendance_date)}</td><td>{events.find((event) => event.id === record.event_id)?.name ?? "Event"}</td><td>{people.find((person) => person.id === record.person_id)?.name ?? "Attendee"}</td><td>{record.status}</td><td>{record.remark ?? "—"}</td></tr>)}</tbody></table>{!records.length ? <p className="empty-state">No recent records.</p> : null}</div></section> : null}
  </main></PortalShell>;
}
