import Link from "next/link";
import { CalendarCheck, CheckCircle2, UserPlus, Users } from "lucide-react";
import { mapAttendancePersonAction, saveAttendanceRecordAction, toggleAttendanceEventAction, toggleAttendancePersonAction } from "@/app/actions/workflows";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { PortalShell } from "@/components/portal-shell";
import { requireProfile } from "@/lib/auth";
import { daysAgoInIndia, displayDate, todayInIndia } from "@/lib/date";
import { getAttendanceEventPeople, getAttendanceEvents, getAttendancePeople, getAttendanceRecords, getProfiles } from "@/lib/data";

export default async function AttendancePage({ searchParams }: { searchParams: Promise<{ eventId?: string; date?: string; created?: string }> }) {
  const profile = await requireProfile();
  const query = await searchParams;
  const students = profile.role === "student" ? [profile] : await getProfiles("student", true);
  const visibleProfileIds = profile.role === "super_admin" ? null : students.map((student) => student.id);
  const [events, people] = await Promise.all([getAttendanceEvents(), getAttendancePeople(visibleProfileIds)]);
  const activeStudentIds = new Set(students.map((student) => student.id));
  const operationalPeople = people.filter((person) => person.is_active && (!person.profile_id || activeStudentIds.has(person.profile_id)));
  const visiblePersonIds = operationalPeople.map((person) => person.id);
  const [mappings, records] = await Promise.all([getAttendanceEventPeople(visiblePersonIds), getAttendanceRecords(daysAgoInIndia(30), visiblePersonIds)]);
  const selectedEvent = events.find((event) => event.id === query.eventId) ?? events[0];
  const selectedDate = /^\d{4}-\d{2}-\d{2}$/.test(query.date ?? "") ? query.date! : todayInIndia();
  const mappedIds = new Set(mappings.filter((item) => item.event_id === selectedEvent?.id).map((item) => item.person_id));
  const eventPeople = operationalPeople.filter((person) => mappedIds.has(person.id));

  return <PortalShell profile={profile}><main className="page-container">
    <header className="page-heading hero-heading"><div><p className="eyebrow">Operations / Attendance</p><h1>{profile.role === "student" ? "My Attendance" : "Attendance"}</h1><p>{profile.role === "student" ? "Review your attendance across hostel events." : "Record attendance and review recent participation."}</p></div>{profile.role === "super_admin" ? <div className="heading-actions"><Link className="button button-secondary" href="/attendance/new-attendee"><UserPlus size={17} aria-hidden="true" /> Add Attendee</Link><Link className="button" href="/attendance/new-event"><CalendarCheck size={17} aria-hidden="true" /> Create Event</Link></div> : null}</header>

    {query.created === "1" && selectedEvent ? <p className="form-message form-success section-feedback" role="status"><CheckCircle2 size={17} aria-hidden="true" /> “{selectedEvent.name}” was created. Add and map attendees to start recording attendance.</p> : null}

    {profile.role !== "student" ? <section className="panel"><form className="filters" method="get"><div className="field"><label htmlFor="eventId">Event</label><select id="eventId" name="eventId" defaultValue={selectedEvent?.id}>{events.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select></div><div className="field"><label htmlFor="date">Date</label><input id="date" name="date" type="date" defaultValue={selectedDate} /></div><button className="button button-secondary">Load Sheet</button></form><div className="panel-title"><h2>{selectedEvent?.name ?? "Attendance Sheet"}</h2><span>{eventPeople.length} {eventPeople.length === 1 ? "attendee" : "attendees"}</span></div><div className="attendance-sheet">{eventPeople.map((person) => { const current = records.find((record) => record.event_id === selectedEvent?.id && record.person_id === person.id && record.attendance_date === selectedDate); return <form action={saveAttendanceRecordAction} className="attendance-row" key={person.id}><input type="hidden" name="eventId" value={selectedEvent?.id} /><input type="hidden" name="personId" value={person.id} /><input type="hidden" name="attendanceDate" value={selectedDate} /><strong>{person.name}</strong><select name="status" aria-label={`Attendance status for ${person.name}`} defaultValue={current?.status ?? selectedEvent?.status_options[0]}>{selectedEvent?.status_options.map((status) => <option key={status} value={status}>{status}</option>)}</select><input name="remark" aria-label={`Remark for ${person.name}`} placeholder="Add a remark…" defaultValue={current?.remark ?? ""} /><button className="button button-small">Save</button></form>; })}{!eventPeople.length ? <div className="empty-state"><Users size={28} aria-hidden="true" /><strong>No Attendees Mapped</strong><p>Map an attendee to this event from Attendance Setup.</p></div> : null}</div></section> : <section className="panel"><div className="panel-title"><h2><Users size={19} aria-hidden="true" /> Attendance History</h2><span>Last 30 days</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Status</th><th>Remark</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{displayDate(record.attendance_date)}</td><td>{events.find((event) => event.id === record.event_id)?.name ?? "Event"}</td><td><span className="status-pill status-success">{record.status}</span></td><td>{record.remark ?? "—"}</td></tr>)}</tbody></table>{!records.length ? <div className="empty-state"><CalendarCheck size={28} aria-hidden="true" /><strong>No Attendance Records</strong><p>Your attendance history will appear here.</p></div> : null}</div></section>}

    {profile.role === "super_admin" ? <section className="panel section-gap"><div className="panel-title"><h2>Attendance Setup</h2><span>Map people and manage active records</span></div>{events.length && operationalPeople.length ? <form action={mapAttendancePersonAction} className="filters"><div className="field"><label htmlFor="map-event">Event</label><select id="map-event" name="eventId" required>{events.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select></div><div className="field"><label htmlFor="map-person">Attendee</label><select id="map-person" name="personId" required>{operationalPeople.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></div><button className="button button-secondary">Add to Event</button></form> : null}<div className="management-grid"><div><h3>Events</h3>{events.map((event) => <form action={toggleAttendanceEventAction} className="management-row" key={event.id}><span>{event.name}</span><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="active" value={event.is_active ? "false" : "true"} />{event.is_active ? <ConfirmSubmitButton className="button button-secondary button-small" message={`Archive “${event.name}”? Existing history will be preserved.`}>Archive</ConfirmSubmitButton> : <button className="button button-secondary button-small">Restore</button>}</form>)}</div><div><h3>Attendees</h3>{people.map((person) => <form action={toggleAttendancePersonAction} className="management-row" key={person.id}><span>{person.name}</span><input type="hidden" name="personId" value={person.id} /><input type="hidden" name="active" value={person.is_active ? "false" : "true"} />{person.is_active ? <ConfirmSubmitButton className="button button-secondary button-small" message={`Archive ${person.name}? Existing attendance history will be preserved.`}>Archive</ConfirmSubmitButton> : <button className="button button-secondary button-small">Restore</button>}</form>)}</div></div></section> : null}

    {profile.role !== "student" ? <section className="panel section-gap"><div className="panel-title"><h2>Recent Records</h2><span>Last 30 days</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Event</th><th>Attendee</th><th>Status</th><th>Remark</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{displayDate(record.attendance_date)}</td><td>{events.find((event) => event.id === record.event_id)?.name ?? "Event"}</td><td>{people.find((person) => person.id === record.person_id)?.name ?? "Attendee"}</td><td>{record.status}</td><td>{record.remark ?? "—"}</td></tr>)}</tbody></table>{!records.length ? <p className="empty-state">No recent records.</p> : null}</div></section> : null}
  </main></PortalShell>;
}
