import Link from "next/link";
import { CalendarCheck, CheckCircle2, Shirt } from "lucide-react";
import { closeWeeklyProgramAction, saveWeeklyEntryAction } from "@/app/actions/workflows";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
import { PortalShell } from "@/components/portal-shell";
import { requireProfile } from "@/lib/auth";
import { displayDate } from "@/lib/date";
import { getProfiles, getWeeklyProgramEntries, getWeeklyPrograms } from "@/lib/data";

export default async function WeeklyProgramPage({ searchParams }: { searchParams: Promise<{ mentorId?: string }> }) {
  const profile = await requireProfile();
  const query = await searchParams;
  const [programs, allStudents, mentors] = await Promise.all([getWeeklyPrograms(), profile.role === "student" ? Promise.resolve([profile]) : getProfiles("student", true), profile.role === "super_admin" ? getProfiles("admin", true) : Promise.resolve([])]);
  const entries = await getWeeklyProgramEntries(allStudents.map((student) => student.id));
  const selectedMentor = mentors.some((mentor) => mentor.id === query.mentorId) ? query.mentorId : undefined;
  const students = selectedMentor ? allStudents.filter((student) => student.mentor_id === selectedMentor) : allStudents;
  const active = programs.find((program) => program.is_active);
  const ownEntry = active ? entries.find((entry) => entry.program_id === active.id && entry.student_id === profile.id) : undefined;
  return <PortalShell profile={profile}><main className="page-container"><header className="page-heading hero-heading"><div><p className="eyebrow">Operations / Weekly Gathering</p><h1>Weekly Program</h1><p>Record participation and review consistent attendance.</p></div><div className="heading-actions">{active ? <span className="status-pill status-success">Active · {displayDate(active.program_date)}</span> : <span className="status-pill status-warning">No active session</span>}{profile.role === "super_admin" ? <Link className="button" href="/weekly-program/new">Open Session</Link> : null}</div></header>
    {profile.role === "student" ? <section className="panel narrow-panel"><div className="panel-title"><h2><CalendarCheck size={20} /> {active ? displayDate(active.program_date) : "Weekly report"}</h2></div>{active ? <form action={saveWeeklyEntryAction} className="form-stack"><input type="hidden" name="programId" value={active.id} /><fieldset className="choice-field"><legend>Weekly Program attendance</legend><label><input type="radio" name="attendance" value="present" defaultChecked={ownEntry?.attendance !== "absent"} /> Present</label><label><input type="radio" name="attendance" value="absent" defaultChecked={ownEntry?.attendance === "absent"} /> Absent</label></fieldset><fieldset className="choice-field"><legend>Were you wearing Dhoti-Kurta?</legend><label><input type="radio" name="woreDhotiKurta" value="true" defaultChecked={ownEntry?.wore_dhoti_kurta !== false} /> Yes</label><label><input type="radio" name="woreDhotiKurta" value="false" defaultChecked={ownEntry?.wore_dhoti_kurta === false} /> No</label></fieldset><button className="button">{ownEntry ? "Update weekly report" : "Submit weekly report"}</button></form> : <p className="empty-state">The Admin has not opened a Weekly Program session.</p>}</section> : null}
    {profile.role === "super_admin" && active ? <section className="panel operational-strip"><div><strong>Active Session</strong><span>{displayDate(active.program_date)} · accepting Student responses</span></div><form action={closeWeeklyProgramAction}><input type="hidden" name="programId" value={active.id} /><ConfirmSubmitButton message="Close this Weekly Program session? Students will no longer be able to update their responses.">Close Session</ConfirmSubmitButton></form></section> : null}
    {profile.role !== "student" ? <section className="panel section-gap"><div className="panel-title"><div><p className="eyebrow">Participation report</p><h2>{profile.role === "admin" ? "My students" : "All students"}</h2></div></div><div className="table-wrap"><table><thead><tr><th>Student</th>{programs.slice(0, 8).map((program) => <th key={program.id}>{displayDate(program.program_date)}</th>)}</tr></thead><tbody>{students.map((student) => <tr key={student.id}><td><strong>{student.full_name}</strong></td>{programs.slice(0, 8).map((program) => { const item = entries.find((entry) => entry.program_id === program.id && entry.student_id === student.id); return <td key={program.id}>{item ? <span className={`status-pill ${item.attendance === "present" ? "status-success" : "status-danger"}`}>{item.attendance === "present" ? <><CheckCircle2 size={13} /> Present{item.wore_dhoti_kurta ? <Shirt size={13} aria-label="Dhoti-Kurta" /> : null}</> : "Absent"}</span> : "Not filled"}</td>; })}</tr>)}</tbody></table></div></section> : null}
    {profile.role === "super_admin" ? <section className="panel section-gap-small"><form className="filters compact-filter"><div className="field"><label htmlFor="mentorId">Filter report by Mentor</label><select id="mentorId" name="mentorId" defaultValue={selectedMentor ?? ""}><option value="">All Mentors</option>{mentors.map((mentor) => <option key={mentor.id} value={mentor.id}>{mentor.full_name}</option>)}</select></div><button className="button button-secondary button-small">Filter</button></form></section> : null}
  </main></PortalShell>;
}
